[package]
name = "tic_tac_toe"
version = "0.1.0"
description = "Tic Tac Toe in Terminal"
authors = ["patricehotz <polarfuchs750@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
itertools = "0.14.0"
